"""empty message

Revision ID: 331320b4f8d1
Revises: b59418d33935
Create Date: 2026-02-20 12:41:58.092954

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "331320b4f8d1"
down_revision: Union[str, Sequence[str], None] = "b59418d33935"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_agent_runs_workspace_ref_id"), table_name="agent_runs")
    op.drop_index(op.f("ix_agent_runs_workspace_scope"), table_name="agent_runs")
    op.drop_column("agent_runs", "workspace_scope")
    op.drop_column("agent_runs", "workspace_ref_id")
    op.drop_index(
        op.f("ix_agent_scheduled_tasks_project_id"), table_name="agent_scheduled_tasks"
    )
    op.drop_index(
        op.f("ix_agent_scheduled_tasks_workspace_scope"),
        table_name="agent_scheduled_tasks",
    )
    op.drop_constraint(
        op.f("agent_scheduled_tasks_project_id_fkey"),
        "agent_scheduled_tasks",
        type_="foreignkey",
    )
    op.drop_column("agent_scheduled_tasks", "project_id")
    op.drop_column("agent_scheduled_tasks", "workspace_scope")
    op.drop_index(
        op.f("ix_agent_sessions_workspace_ref_id"), table_name="agent_sessions"
    )
    op.drop_index(
        op.f("ix_agent_sessions_workspace_scope"), table_name="agent_sessions"
    )
    op.drop_column("agent_sessions", "workspace_scope")
    op.drop_column("agent_sessions", "workspace_ref_id")
    op.add_column("plugins", sa.Column("source", sa.JSON(), nullable=True))
    op.add_column("skills", sa.Column("source", sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("skills", "source")
    op.drop_column("plugins", "source")
    op.add_column(
        "agent_sessions",
        sa.Column("workspace_ref_id", sa.UUID(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "agent_sessions",
        sa.Column(
            "workspace_scope",
            sa.VARCHAR(length=50),
            server_default=sa.text("'session'::character varying"),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.create_index(
        op.f("ix_agent_sessions_workspace_scope"),
        "agent_sessions",
        ["workspace_scope"],
        unique=False,
    )
    op.create_index(
        op.f("ix_agent_sessions_workspace_ref_id"),
        "agent_sessions",
        ["workspace_ref_id"],
        unique=False,
    )
    op.add_column(
        "agent_scheduled_tasks",
        sa.Column(
            "workspace_scope",
            sa.VARCHAR(length=50),
            server_default=sa.text("'session'::character varying"),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.add_column(
        "agent_scheduled_tasks",
        sa.Column("project_id", sa.UUID(), autoincrement=False, nullable=True),
    )
    op.create_foreign_key(
        op.f("agent_scheduled_tasks_project_id_fkey"),
        "agent_scheduled_tasks",
        "projects",
        ["project_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.create_index(
        op.f("ix_agent_scheduled_tasks_workspace_scope"),
        "agent_scheduled_tasks",
        ["workspace_scope"],
        unique=False,
    )
    op.create_index(
        op.f("ix_agent_scheduled_tasks_project_id"),
        "agent_scheduled_tasks",
        ["project_id"],
        unique=False,
    )
    op.add_column(
        "agent_runs",
        sa.Column("workspace_ref_id", sa.UUID(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "agent_runs",
        sa.Column(
            "workspace_scope",
            sa.VARCHAR(length=50),
            server_default=sa.text("'session'::character varying"),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.create_index(
        op.f("ix_agent_runs_workspace_scope"),
        "agent_runs",
        ["workspace_scope"],
        unique=False,
    )
    op.create_index(
        op.f("ix_agent_runs_workspace_ref_id"),
        "agent_runs",
        ["workspace_ref_id"],
        unique=False,
    )
    # ### end Alembic commands ###
